# Generated by Django 4.0.5 on 2022-07-13 09:23

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.models.get_avatar_file_path, verbose_name='Ваше фото'),
        ),
    ]
