# Generated by Django 4.0.5 on 2022-07-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='status',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='status',
            new_name='published',
        ),
    ]
