# Generated by Django 4.0.5 on 2022-07-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='delivery',
        ),
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(default=12, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Бесплатная доставка от, руб.'),
        ),
    ]
