# Generated by Django 4.0.5 on 2022-07-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_status_category_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published',
            field=models.CharField(choices=[('checking', 'На проверке'), ('yes', 'Опубликован'), ('no', 'Отклонён')], default='checking', max_length=8, verbose_name='Статус отзыва'),
        ),
    ]
