# Generated by Django 4.0.5 on 2022-06-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review_author_review_status_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
