# Generated by Django 4.0.5 on 2022-07-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_review_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='product_mtm',
            field=models.ManyToManyField(related_name='images_mtm', to='core.product'),
        ),
    ]
