# Generated by Django 4.0.5 on 2022-07-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_setting_name_alter_setting_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='quantity',
            new_name='delivery',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='name',
        ),
    ]
