# Generated by Django 4.0.5 on 2022-07-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productimage_product_mtm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_mtm',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ManyToManyField(related_name='reviews', to='core.product'),
        ),
    ]
