# Generated by Django 4.0.5 on 2022-07-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_quantity_setting_delivery_remove_setting_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
