# Generated by Django 4.0.5 on 2022-07-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Настройки')),
                ('delivery', models.PositiveIntegerField(default=0, verbose_name='Бесплатная доставка от, руб.')),
            ],
        ),
    ]
