# Generated by Django 4.0.5 on 2022-07-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_reviews_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviews', to='core.product', verbose_name='Продукт'),
        ),
    ]
