# Generated by Django 4.0.5 on 2022-07-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AddField(
            model_name='setting',
            name='delivery_free',
            field=models.PositiveIntegerField(default=0, verbose_name='Бесплатная доставка от, руб.'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='delivery',
            field=models.PositiveIntegerField(default=0, verbose_name='Доставка, руб.'),
        ),
    ]
