# Generated by Django 4.0.5 on 2022-07-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderitem_created_orderitem_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Стоимость заказа, руб'),
            preserve_default=False,
        ),
    ]
