# Generated by Django 4.0.5 on 2022-07-29 05:39

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_delivery_order_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, upload_to=apps.core.models.get_product_image_file_path, verbose_name='Фотографии'),
        ),
    ]
