# Generated by Django 4.0.5 on 2022-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '<i class="bi bi-star-fill"></i>'), (2, 'Ii'), (3, 'Iii'), (4, 'Iv'), (5, 'V')], max_length=1, verbose_name='Рейтинг'),
        ),
    ]
