# Generated by Django 4.0.5 on 2022-07-30 06:19

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Ваш e-mail')),
                ('message', models.TextField(blank=True, default=None, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, upload_to=apps.core.models.get_product_image_file_path, verbose_name='Фотография'),
        ),
    ]
