# Generated by Django 4.0.5 on 2022-07-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(related_name='reviews', to='core.review', verbose_name='Отзывы'),
        ),
    ]
