# Generated by Django 4.0.5 on 2022-07-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_product_review_remove_review_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(related_name='reviews', to='core.review', verbose_name='Отзывы'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product', verbose_name='Продукт'),
        ),
    ]
