# Generated by Django 4.0.5 on 2022-07-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_orderitem_options_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=5, max_length=1, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
