# Generated by Django 4.0.5 on 2022-07-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product_review_remove_review_product_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
    ]
