# Generated by Django 4.0.5 on 2022-07-12 06:29

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to=apps.core.models.get_category_file_path, verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to=apps.core.models.get_product_file_path, verbose_name='Изображение обложки'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to=apps.core.models.get_product_image_file_path, verbose_name='Фотографии'),
        ),
    ]
