# Generated by Django 4.0.5 on 2022-08-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
