# Generated by Django 4.0.5 on 2022-08-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_product_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('gram', 'грамм'), ('piece', 'штука'), ('set', 'комплект')], default='gram', max_length=10, verbose_name='Единица измерения объёма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(verbose_name='Количество (объём)'),
        ),
    ]
