# Generated by Django 4.0.5 on 2022-06-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Чай'), ('2', 'Кофе'), ('3', 'Специи')], default='1', max_length=3, verbose_name='Категория')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('town', models.CharField(max_length=50, verbose_name='Город')),
                ('year', models.CharField(max_length=50, verbose_name='Год')),
                ('volume', models.IntegerField(verbose_name='Вес')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('tag', models.CharField(max_length=100, verbose_name='Метки')),
                ('talk_forum', models.URLField(verbose_name='Ссылка на форум')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
