# Generated by Django 4.0.5 on 2022-06-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_country_alter_product_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена, руб'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Метки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='talk_forum',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на форум'),
        ),
        migrations.AlterField(
            model_name='product',
            name='town',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.IntegerField(verbose_name='Вес, грамм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Год'),
        ),
    ]
