# Generated by Django 4.0.5 on 2022-06-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_category_name_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Чай'), ('2', 'Кофе'), ('3', 'Специи')], default='1', max_length=20, verbose_name='Категория'),
        ),
    ]
