# Generated by Django 4.0.5 on 2022-06-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на Категорию'),
        ),
    ]
