# Generated by Django 4.0.5 on 2022-06-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
