# Generated by Django 4.0.5 on 2022-06-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(max_length=100, null=True, verbose_name='Метки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='talk_forum',
            field=models.URLField(null=True, verbose_name='Ссылка на форум'),
        ),
        migrations.AlterField(
            model_name='product',
            name='town',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.CharField(max_length=50, null=True, verbose_name='Год'),
        ),
    ]
