# Generated by Django 4.0.5 on 2022-06-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Ссылка на Категорию'),
        ),
    ]
