# Generated by Django 4.0.5 on 2022-06-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_comment_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Review',
        ),
    ]
