# Generated by Django 4.0.5 on 2022-06-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_comment_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='product',
        ),
    ]
